// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utrllwoyhdadqiknvnln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0cmxsd295aGRhZHFpa252bmxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MDA3NzYsImV4cCI6MjA2MzI3Njc3Nn0.V0dVt_74xTG7L-i4Tz2yhjL4L6ta78DhJoh61P9ECHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);